#!/bin/bash
SCRIPTPATH=$(dirname $(realpath $0))

LIST="172.16.1.110 172.16.1.111 172.16.1.112 172.16.1.113 172.16.1.114 172.16.1.147 172.16.1.148 172.16.1.149 172.16.1.150"

BUILD=$(printf "[")
for i in $LIST
 do
 RESPONSE=$(printf "{\"HOST\":\"$i\",\""; $SCRIPTPATH/api.pl -c summary -a $i -p 4068 | tr -d '\0' | sed -r 's/=/":"/g; s/;/\",\"/g' | sed 's/|/",/g')$(printf "\""; $SCRIPTPATH/api.pl -c pool -a $i -p 4068 | tr -d '\0' | sed -r 's/=/":"/g' | sed -r 's/;/\",\"/g' | sed 's/|/"},/g')
 if [[ "$RESPONSE" == *"No Connect"* ]]
 then
  BUILD=$BUILD"{\"HOST\":\"$i\"},"
 else
  BUILD=$BUILD$RESPONSE
 fi
done
JSON=$(echo $BUILD | tr -d '\r\n' | sed "s/.\{0,2\}$//; /^$/d"; printf "}]")
echo $JSON | jq '[.[] | {HOST,POOL,USER,KHS,DIFF,ACC,REJ,WAIT,UPTIME,TS}]'
